name: Schedule Python Script

on:
  schedule:
    - cron: '0 16 * * *'  # Every day at 2:40 AM UTC
  workflow_dispatch:  # Add this line to allow manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python nse-block-deals.py
      - name: Upload block deals report
        uses: actions/upload-artifact@v2
        with:
          name: block-deals
          path: block_deals_*.csv
